"""Self-host the IBM Plex fonts and write assets/css/fonts.css.

    python -m tools.fonts          # download (if missing) and rewrite fonts.css

Why self-hosted: one origin instead of two Google round trips, and no text
jump. Each web font gets a metric-matched local fallback ("... Fallback",
built on Arial / Courier New), so the text laid out before the web font
arrives takes the same space as the text after it; the swap no longer shifts
the page. The override values are computed from the font files themselves.

IBM Plex is SIL Open Font License 1.1: self-hosting is permitted.
Needs: pip install fonttools brotli   (only to run this, not to serve the site)
"""

from __future__ import annotations

import pathlib
import re
import sys
import urllib.request

from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "assets" / "fonts"
CSS = ROOT / "assets" / "css" / "fonts.css"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0 Safari/537.36")

FAMILIES = {
    # family: (google css query, subsets kept, fallback file, fallback local name)
    "IBM Plex Sans": ("IBM+Plex+Sans:wght@300;400;500;600", ("latin", "latin-ext"),
                      "C:/Windows/Fonts/arial.ttf", "Arial"),
    "IBM Plex Mono": ("IBM+Plex+Mono:wght@400;500", ("latin", "latin-ext"),
                      "C:/Windows/Fonts/cour.ttf", "Courier New"),
    "IBM Plex Sans Arabic": ("IBM+Plex+Sans+Arabic:wght@300;400;500;600", ("arabic", "latin"),
                             "C:/Windows/Fonts/arial.ttf", "Arial"),
}
FALLBACK_NAME = {"IBM Plex Sans": "Plex Sans Fallback",
                 "IBM Plex Mono": "Plex Mono Fallback",
                 "IBM Plex Sans Arabic": "Plex Arabic Fallback"}

LATIN_SAMPLE = "etaoinshrdlucmfwypvbgkjqxz "
ARABIC_SAMPLE = "المينوتربعهسدكفقحجشصطضذخثزظغ "

FACE = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", re.S)


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def slug(family: str) -> str:
    return family.lower().replace(" ", "-")


def metrics(path, sample: str = "etaoinshrdlucmfwypvbgkjqxz ") -> dict:
    f = TTFont(path)
    upm = f["head"].unitsPerEm
    os2, hhea = f["OS/2"], f["hhea"]
    # average advance over a sample of lowercase + space, weighted like
    # running English text, is a better width proxy than xAvgCharWidth
    cmap = f.getBestCmap()
    hmtx = f["hmtx"]
    widths = [hmtx[cmap[ord(c)]][0] for c in sample if ord(c) in cmap]
    return {"upm": upm, "asc": hhea.ascent, "desc": -hhea.descent, "gap": hhea.lineGap,
            "avg": sum(widths) / len(widths) / upm}


def main(argv: list[str]) -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    blocks = ["/* IBM Plex, self-hosted (SIL OFL 1.1). Generated by tools/fonts -- edit\n"
              "   tools/fonts/build.py, not this file. Each family has a metric-matched\n"
              "   local fallback so the swap to the web font does not move the text. */\n"]
    for family, (query, keep, fb_file, fb_local) in FAMILIES.items():
        css = fetch(f"https://fonts.googleapis.com/css2?family={query}&display=swap").decode()
        ref = None
        for subset, body in FACE.findall(css):
            if subset not in keep:
                continue
            weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
            url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
            rng = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()
            name = f"{slug(family)}-{weight}-{subset}.woff2"
            dest = OUT / name
            if not dest.exists():
                dest.write_bytes(fetch(url))
            if ref is None or (weight == "400" and subset == keep[0]):  # the primary script's regular
                ref = dest
            blocks.append(
                f"@font-face{{font-family:'{family}';font-style:normal;font-weight:{weight};"
                f"font-display:swap;src:url('/assets/fonts/{name}') format('woff2');"
                f"unicode-range:{rng}}}")
        sample = ARABIC_SAMPLE if "Arabic" in family else LATIN_SAMPLE
        web, fb = metrics(ref, sample), metrics(fb_file, sample)
        size = web["avg"] / fb["avg"]
        blocks.append(
            f"@font-face{{font-family:'{FALLBACK_NAME[family]}';src:local('{fb_local}');"
            f"size-adjust:{size * 100:.2f}%;"
            f"ascent-override:{web['asc'] / web['upm'] / size * 100:.2f}%;"
            f"descent-override:{web['desc'] / web['upm'] / size * 100:.2f}%;"
            f"line-gap-override:{web['gap'] / web['upm'] / size * 100:.2f}%}}")
    CSS.write_text("\n".join(blocks) + "\n", encoding="utf-8", newline="")
    files = sorted(OUT.glob("*.woff2"))
    print(f"fonts    : {len(files)} files, {sum(f.stat().st_size for f in files) // 1024} KB; "
          f"{CSS.relative_to(ROOT).as_posix()} written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
