"""Inject tools/mobile/mobile.css into every page's inline <style>.

The export has no shared stylesheet -- each of the 108 files carries its own
<style> block -- so the mobile rules are appended to each one between markers.
Idempotent: running twice writes zero files.

    python -m tools.mobile          # apply
    python -m tools.mobile --check  # report drift without writing

The Arabic pages get the same block. Everything in it is direction-neutral
(sizes and wrapping, no left/right offsets), so it needs no RTL counterpart;
assets/rtl.css keeps owning direction.
"""

from __future__ import annotations

import pathlib
import re
import sys

BEGIN = "/* mobile:begin  generated by tools/mobile -- edit tools/mobile/mobile.css */"
END = "/* mobile:end */"

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = pathlib.Path(__file__).resolve().parent / "mobile.css"

BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)


def pages(root: pathlib.Path) -> list[str]:
    out = []
    for p in sorted(root.rglob("*.html")):
        rel = p.relative_to(root).as_posix()
        if rel.startswith("tools/") or rel == "404.html":
            continue  # 404.html is self-contained and outside the page set
        out.append(rel)
    return out


def block() -> str:
    css = SRC.read_text(encoding="utf-8").strip()
    return f"{BEGIN}\n{css}\n{END}"


def inject(s: str, blk: str) -> str:
    """Replace the managed block, or append it to the last <style> in <head>."""
    if BLOCK_RE.search(s):
        return BLOCK_RE.sub(lambda _: blk, s, count=1)

    head_end = s.lower().find("</head>")
    # the last </style> before </head>: the page's own rules must win over
    # nothing here, but the mobile block has to come after them so equal
    # specificity resolves in its favour
    i = s.lower().rfind("</style>", 0, head_end if head_end > 0 else len(s))
    if i < 0:
        return s
    return s[:i] + "\n" + blk + "\n" + s[i:]


def run(root: pathlib.Path, check: bool = False) -> dict:
    blk = block()
    changed, missing = [], []
    for rel in pages(root):
        p = root / rel
        s0 = p.read_text(encoding="utf-8")
        s = inject(s0, blk)
        if s == s0:
            continue
        if BLOCK_RE.search(s0) is None and "</style>" not in s0.lower():
            missing.append(rel)
            continue
        changed.append(rel)
        if not check:
            p.write_text(s, encoding="utf-8", newline="")
    return {"pages": len(pages(root)), "changed": changed, "no_style_tag": missing}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    r = run(ROOT, check=check)
    verb = "would change" if check else "rewritten"
    print(f"mobile   : {r['pages']} pages, {len(r['changed'])} {verb}")
    for rel in r["no_style_tag"]:
        print(f"           SKIPPED {rel}: no <style> block to append to")
    return 1 if (check and r["changed"]) else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
