"""Turn published posts into article pages and list them on Perspectives.

    python -m tools.blog            # build: pages + listing rows (then run tools.seo build)
    python -m tools.blog clean      # remove everything this generates (before committing by hand)

For each published post in content/posts/:
  research/perspectives/<slug>/index.html       English article
  ar/research/perspectives/<slug>/index.html    Arabic article, when the post has an Arabic title and body
and a row at the top of the Perspectives listing (English, and Arabic for posts
that have Arabic).

The page shell (head, nav, drawer, footer, scripts) is taken from the
Perspectives listing page at build time, so articles always match the site
and pick up any nav or footer change. tools/seo then adds the managed SEO head,
Article schema and sitemap entries (tools/seo/pages.py reads the same posts).

Generated pages carry <meta name="generator" content="orvix-blog"> and are not
committed (see .gitignore): Netlify runs this on every deploy, after the admin
commits a post.
"""

from __future__ import annotations

import datetime
import html
import pathlib
import re
import shutil
import sys

from . import markdown, posts

ROOT = posts.ROOT
LISTING = {"en": "research/perspectives/index.html", "ar": "ar/research/perspectives/index.html"}
MARK = '<meta name="generator" content="orvix-blog">'
BEGIN, END = "<!-- blog:begin  generated by tools/blog -->", "<!-- blog:end -->"
R_BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
SEO = re.compile(r"<!-- seo:begin.*?<!-- seo:end -->\n?", re.S)
ATTR = re.compile(r'\b(href|src)="(?!/|#|https?:|mailto:|tel:|data:)([^"]*)"')

COPY = {
    "en": {"label": "Perspective", "back": "← All perspectives", "read": "READ →", "k": "PERSPECTIVE",
           "min": lambda n: f"{n} min read", "brand": "Orvix"},
    "ar": {"label": "وجهة نظر", "back": "→ كل وجهات النظر", "read": "اقرأ ←", "k": "وجهة نظر",
           "min": lambda n: "دقيقة قراءة" if n == 1 else f"{n} دقائق قراءة", "brand": "أورفكس"},
}
MONTHS_EN = ["January", "February", "March", "April", "May", "June", "July", "August",
             "September", "October", "November", "December"]
MONTHS_AR = ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس",
             "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"]


def esc(s: str) -> str:
    return html.escape(s or "", quote=True)


def nice_date(iso: str, lang: str) -> str:
    d = datetime.date.fromisoformat(iso)
    return f"{d.day} {(MONTHS_AR if lang == 'ar' else MONTHS_EN)[d.month - 1]} {d.year}"


def has_lang(p: dict, lang: str) -> bool:
    return lang == "en" or bool(p["title"].get("ar") and p["body"].get("ar"))


def page_rel(slug: str, lang: str) -> str:
    return ("ar/" if lang == "ar" else "") + f"research/perspectives/{slug}/index.html"


# ---- the shell ---------------------------------------------------------------

def shell(lang: str) -> tuple[str, str, str]:
    """(head, top of body up to the content, bottom from the footer) of the listing page,
    with relative paths moved one level deeper."""
    s = (ROOT / LISTING[lang]).read_text(encoding="utf-8")
    head_end = s.find("</head>")
    body_start = s.find(">", s.find("<body")) + 1
    content = s.find('<div class="wwd rsh">', body_start)
    footer = s.find("<footer>", content)
    deeper = lambda part: ATTR.sub(lambda m: f'{m.group(1)}="../{m.group(2)}"', part)
    head = deeper(s[:head_end])
    top = deeper(s[head_end:content])
    bottom = deeper(s[footer:])
    head = SEO.sub("", head)
    head = re.sub(r"<title>.*?</title>\n?", "", head, flags=re.S)
    head = re.sub(r'<meta name="description"[^>]*>\n?', "", head)
    head = re.sub(r'<link rel="preload" as="image"[^>]*>\n?', "", head)
    head = re.sub(r"<style>\s*:root\{\s*--p[hg]-.*?</style>\n?", "", head, flags=re.S)
    return head, top, bottom


def lang_switch(top: str, lang: str, slug: str, twin: bool) -> str:
    """Point the header and drawer language links at this article's twin."""
    if not twin:
        return top
    target = "research/perspectives/"
    def fix(m):
        href = m.group(2)
        return m.group(1) + (href + slug + "/" if href.endswith(target) else href) + m.group(3)
    top = re.sub(r'(<a class="nav-ar" href=")([^"]*)(")', fix, top)
    top = re.sub(r'(<a href=")([^"]*)(" lang="(?:ar|en)")', fix, top)
    return top


def strip_cta(lang: str) -> str:
    s = (ROOT / LISTING[lang]).read_text(encoding="utf-8")
    m = re.search(r'<section class="nl"[^>]*>.*?</section>', s, re.S)
    return ATTR.sub(lambda m: f'{m.group(1)}="../{m.group(2)}"', m.group(0)) if m else ""


# ---- one article ------------------------------------------------------------

def article(p: dict, lang: str) -> str:
    c = COPY[lang]
    slug = p["slug"]
    title, summary = p["title"][lang], p["summary"][lang] or p["summary"]["en"]
    body = p["body"][lang]
    mins = max(1, round(markdown.plain_words(body) / 220))
    head, top, bottom = shell(lang)
    twin = has_lang(p, "ar" if lang == "en" else "en")
    top = lang_switch(top, lang, slug, twin)

    cover = p.get("cover") or ""
    cover_ok = cover.startswith("/images/posts/") and (ROOT / cover.lstrip("/")).is_file()
    extra = [MARK, f"<title>{esc(title)} | {c['brand']}</title>",
             f'<meta name="description" content="{esc(summary)}">']
    if cover_ok:
        # the cover is the banner background, exactly like the site's photo heroes
        # (.wwd .hero::before reads --pg-hero; the ::after scrim keeps text legible)
        extra.append(f'<link rel="preload" as="image" href="{esc(cover)}" fetchpriority="high">')
        extra.append(f"<style>:root{{--pg-hero:url('{esc(cover)}')}}</style>")
    i = head.find('<link rel="stylesheet"')
    head = head[:i] + "\n".join(extra) + "\n" + head[i:] if i > 0 else head + "\n".join(extra)
    # last, so it layers over the template stylesheets (and rtl.css) it builds on
    head = head.rstrip("\n") + '\n<link rel="stylesheet" href="/assets/css/article.css">\n'

    # the banner photo is a CSS background, so its description is given to
    # screen readers on the banner itself
    alt = (p.get("cover_alt", {}).get(lang) or "") if cover_ok else ""
    figure = f'<p class="sr-only">{esc(alt)}</p>' if alt else ""
    main = (
        '<div class="wwd rsh post-page">'
        '<header class="hero nocrumb"><div class="w">'
        f'<h1><span class="lbl">{c["label"]}</span> {esc(title)}</h1>'
        f'<p class="sub">{esc(summary)}</p>'
        f'<p class="post-meta"><time datetime="{esc(p["published"])}">{nice_date(p["published"], lang)}</time>'
        f'<span aria-hidden="true">·</span><span>{esc(p.get("author") or "Orvix")}</span>'
        f'<span aria-hidden="true">·</span><span>{c["min"](mins)}</span></p>'
        '</div></header>'
        '<article class="post"><div class="w">'
        f'{figure}<div class="post-body">\n{markdown.render(body)}\n</div>'
        f'<p class="post-back"><a href="../">{c["back"]}</a></p>'
        '</div></article>'
        f'{strip_cta(lang)}'
        '</div>\n'
    )
    return head + top + main + bottom


# ---- the listing ------------------------------------------------------------

def rows(ps: list[dict], lang: str) -> str:
    c = COPY[lang]
    out = []
    for p in ps:
        if not has_lang(p, lang):
            continue
        out.append(
            f'<a class="row post" href="{esc(p["slug"])}/">'
            f'<div class="k">{c["k"]} · {nice_date(p["published"], lang)}</div>'
            f'<div><h3>{esc(p["title"][lang])}</h3><p>{esc(p["summary"][lang] or p["summary"]["en"])}</p></div>'
            f'<div class="go">{c["read"]}</div></a>')
    return BEGIN + "".join(out) + END


def set_listing(lang: str, ps: list[dict]) -> bool:
    f = ROOT / LISTING[lang]
    s0 = s = f.read_text(encoding="utf-8")
    block = rows(ps, lang)
    if R_BLOCK.search(s):
        s = R_BLOCK.sub(lambda _: block, s, count=1)
    else:
        s = s.replace('<div class="lst">', '<div class="lst">' + block, 1)
    if s != s0:
        f.write_text(s, encoding="utf-8", newline="")
    return s != s0


# ---- build / clean ----------------------------------------------------------

def generated_dirs() -> list[pathlib.Path]:
    out = []
    for lang in ("en", "ar"):
        base = ROOT / pathlib.Path(LISTING[lang]).parent
        for d in base.iterdir() if base.is_dir() else []:
            f = d / "index.html"
            if d.is_dir() and f.is_file() and MARK in f.read_text(encoding="utf-8")[:4000]:
                out.append(d)
    return out


def build() -> dict:
    ps = posts.published()
    keep = set()
    for p in ps:
        for lang in ("en", "ar"):
            if not has_lang(p, lang):
                continue
            rel = page_rel(p["slug"], lang)
            f = ROOT / rel
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(article(p, lang), encoding="utf-8", newline="")
            keep.add(f.parent.resolve())
    removed = 0
    for d in generated_dirs():
        if d.resolve() not in keep:
            shutil.rmtree(d)
            removed += 1
    for lang in ("en", "ar"):
        set_listing(lang, ps)
    return {"published": len(ps), "pages": len(keep), "removed": removed}


def clean() -> dict:
    n = 0
    for d in generated_dirs():
        shutil.rmtree(d)
        n += 1
    for lang in ("en", "ar"):
        set_listing(lang, [])
    return {"removed": n}


def main(argv: list[str]) -> int:
    if len(argv) > 1 and argv[1] == "clean":
        r = clean()
        print(f"blog     : removed {r['removed']} generated pages, listing rows cleared")
        return 0
    r = build()
    print(f"blog     : {r['published']} published posts, {r['pages']} pages written, {r['removed']} stale removed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
