"""The one shared <head> component (SEO brief section 2).

Every page's SEO head is emitted from here. Nothing is hand-written per page;
the per-page dict comes from pages.py and the URLs from urls.py, so a rule
change lands on all 108 pages at once.

The output is wrapped in SEO_BEGIN/SEO_END markers. apply.py replaces whatever
sits between them, which makes the rewrite idempotent and keeps the hand-built
<style>, font links and BUILD NOTES in each file untouched.
"""

from __future__ import annotations

import html

from . import urls
from .pages import NOINDEX

SEO_BEGIN = "<!-- seo:begin  generated by tools/seo -- edit tools/seo/pages.py, not this block -->"
SEO_END = "<!-- seo:end -->"

THEME_COLOR = "#03072C"
OG_IMAGE_DIR = "/assets/img/og/"
DEFAULT_OG_IMAGE = "/assets/img/og/default.png"

LOCALE = {"en": "en_AE", "ar": "ar_AE"}


def esc(s: str) -> str:
    """Escape for an HTML attribute value."""
    return html.escape(s, quote=True)


def og_image_for(rel: str) -> str:
    """Absolute og:image URL. One card per page, named after its URL path."""
    en = rel[3:] if rel.startswith("ar/") else rel
    slug = urls.to_url_path(en).strip("/").replace("/", "--") or "home"
    return f"{urls.ORIGIN}{OG_IMAGE_DIR}{slug}.png"


def render(rel: str, page: dict, *, title: str, description: str,
           twin_exists: bool) -> str:
    """The full managed head block for one page."""
    lang = urls.lang_of(rel)
    url = urls.to_url(rel)
    robots = page.get("robots")
    indexable = robots != NOINDEX

    L: list[str] = [SEO_BEGIN]
    A = L.append

    A(f"<title>{esc(title)}</title>")
    A(f'<meta name="description" content="{esc(description)}">')
    A(f'<link rel="canonical" href="{url}">')
    A(f'<meta name="robots" content="{robots}">')

    # hreflang: only when both language URLs exist, never to a page that is not
    # there (section 2). x-default points at English.
    if twin_exists:
        en_rel = rel[3:] if rel.startswith("ar/") else rel
        ar_rel = urls.twin(en_rel)
        A(f'<link rel="alternate" hreflang="en" href="{urls.to_url(en_rel)}">')
        A(f'<link rel="alternate" hreflang="ar" href="{urls.to_url(ar_rel)}">')
        A(f'<link rel="alternate" hreflang="x-default" href="{urls.to_url(en_rel)}">')

    img = page.get("og_image") or og_image_for(rel)
    A(f'<meta property="og:type" content="{page.get("og_type", "website")}">')
    A(f'<meta property="og:title" content="{esc(title)}">')
    A(f'<meta property="og:description" content="{esc(description)}">')
    A(f'<meta property="og:url" content="{url}">')
    A(f'<meta property="og:site_name" content="Orvix">')
    A(f'<meta property="og:locale" content="{LOCALE[lang]}">')
    if twin_exists:
        other = "ar" if lang == "en" else "en"
        A(f'<meta property="og:locale:alternate" content="{LOCALE[other]}">')
    A(f'<meta property="og:image" content="{img}">')
    A(f'<meta property="og:image:width" content="1200">')
    A(f'<meta property="og:image:height" content="630">')
    A(f'<meta property="og:image:alt" content="{esc(title)}">')

    A(f'<meta name="twitter:card" content="summary_large_image">')
    A(f'<meta name="twitter:title" content="{esc(title)}">')
    A(f'<meta name="twitter:description" content="{esc(description)}">')
    A(f'<meta name="twitter:image" content="{img}">')

    A(f'<meta name="theme-color" content="{THEME_COLOR}">')
    A('<link rel="icon" href="/favicon.ico" sizes="48x48">')
    A('<link rel="icon" href="/favicon.svg" type="image/svg+xml">')
    A('<link rel="apple-touch-icon" href="/apple-touch-icon.png">')
    A('<link rel="manifest" href="/site.webmanifest">')
    A('<meta name="referrer" content="strict-origin-when-cross-origin">')

    if not indexable and page.get("noindex_reason"):
        A(f"<!-- noindex: {page['noindex_reason']} -->")

    A(SEO_END)
    return "\n".join(L)
