"""sitemap.xml and robots.txt (SEO brief section 4).

The sitemap is regenerated from the page table, so a page that goes noindex
leaves the sitemap in the same commit rather than in a later cleanup. lastmod
comes from the file's own mtime, which is the only honest date available in a
static export -- there is no publication date recorded anywhere in the HTML.

robots.txt allows the assistant crawlers named in section 4. They are listed
explicitly rather than relying on the wildcard, because being cited by an
assistant is a stated goal of the keyword strategy and an explicit allow is
what survives someone later tightening the wildcard.
"""

from __future__ import annotations

import datetime
import pathlib
import xml.sax.saxutils as sx

from . import urls
from .pages import NOINDEX, for_path

AI_CRAWLERS = ["GPTBot", "ClaudeBot", "PerplexityBot", "Google-Extended", "OAI-SearchBot"]

# Rough relative weight. Not a ranking signal on its own; it just stops every
# page claiming to be as important as the homepage.
PRIORITY = {
    "home": "1.0", "pillar": "0.9", "industry": "0.8", "engagement": "0.8",
    "service": "0.7", "research-item": "0.6", "research": "0.6",
    "listing": "0.5", "company": "0.5",
}


def entries(root: pathlib.Path) -> list[tuple[str, str, str]]:
    """(url, lastmod, priority) for every indexable page, English first."""
    out = []
    for rel in urls.discover(root):
        page = for_path(rel)
        if page is None or page.get("robots") == NOINDEX:
            continue
        st = (root / rel).stat().st_mtime
        lastmod = datetime.datetime.fromtimestamp(st, datetime.timezone.utc).date().isoformat()
        out.append((urls.to_url(rel), lastmod, PRIORITY.get(page["kind"], "0.5")))
    return sorted(out)


def sitemap_xml(root: pathlib.Path) -> str:
    rows = entries(root)
    L = ['<?xml version="1.0" encoding="UTF-8"?>',
         '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
         '        xmlns:xhtml="http://www.w3.org/1999/xhtml">']
    have = {u for u, _, _ in rows}
    for url, lastmod, prio in rows:
        L.append("  <url>")
        L.append(f"    <loc>{sx.escape(url)}</loc>")
        L.append(f"    <lastmod>{lastmod}</lastmod>")
        L.append(f"    <priority>{prio}</priority>")
        # hreflang pairs, but only to URLs that are actually in the sitemap
        path = url[len(urls.ORIGIN):]
        en_url = urls.ORIGIN + (path[3:] if path.startswith("/ar/") else path)
        ar_url = urls.ORIGIN + ("/ar" + path if not path.startswith("/ar/") else path)
        if en_url in have and ar_url in have:
            L.append(f'    <xhtml:link rel="alternate" hreflang="en" href="{sx.escape(en_url)}"/>')
            L.append(f'    <xhtml:link rel="alternate" hreflang="ar" href="{sx.escape(ar_url)}"/>')
            L.append(f'    <xhtml:link rel="alternate" hreflang="x-default" href="{sx.escape(en_url)}"/>')
        L.append("  </url>")
    L.append("</urlset>")
    return "\n".join(L) + "\n"


def robots_txt() -> str:
    L = ["# https://orvixnet.com/robots.txt",
         "# Generated by tools/seo -- edit tools/seo/sitemap.py, not this file.",
         "",
         "User-agent: *",
         "Allow: /",
         ""]
    for bot in AI_CRAWLERS:
        L += [f"User-agent: {bot}", "Allow: /", ""]
    L += [f"Sitemap: {urls.ORIGIN}/sitemap.xml", ""]
    return "\n".join(L)


def write(root: pathlib.Path) -> dict:
    sm = sitemap_xml(root)
    (root / "sitemap.xml").write_text(sm, encoding="utf-8", newline="")
    (root / "robots.txt").write_text(robots_txt(), encoding="utf-8", newline="")
    return {"urls": sm.count("<loc>"), "excluded": len(urls.discover(root)) - sm.count("<loc>")}
